import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>AR-Travels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='w-full'>
          <img className='w-full' src="https://i1.wp.com/www.ecouttarakhand.com/wp-content/uploads/2020/12/char-dham-yatra.jpeg?w=880&ssl=1" alt="" />
        </div>
      </main>
    </>
  )
}
